services:
  pipeline:
    build: ./pipeline
    volumes:
      - ./data:/app/data:ro
      - ./kpis:/app/kpis

  visual:
    build: ./visual
    ports: 
      - "3000:3000"
    volumes:
      - ./kpis:/app/public/kpis:ro
    depends_on:
      - pipeline
